import { Board } from '../types/index';

export const Difficulties = Object.freeze({
  EASY: 'easy',
  MEDIUM: 'medium',
  HARD: 'hard',
});

export const emptyBoard: Board = {
  A2: { value: '' },
  A1: { value: '' },
  A3: { value: '' },
  A4: { value: '' },
  A5: { value: '' },
  A6: { value: '' },
  A7: { value: '' },
  A8: { value: '' },
  A9: { value: '' },

  B1: { value: '' },
  B2: { value: '' },
  B3: { value: '' },
  B4: { value: '' },
  B5: { value: '' },
  B6: { value: '' },
  B7: { value: '' },
  B8: { value: '' },
  B9: { value: '' },

  C1: { value: '' },
  C2: { value: '' },
  C3: { value: '' },
  C4: { value: '' },
  C5: { value: '' },
  C6: { value: '' },
  C7: { value: '' },
  C8: { value: '' },
  C9: { value: '' },

  D1: { value: '' },
  D2: { value: '' },
  D3: { value: '' },
  D4: { value: '' },
  D5: { value: '' },
  D6: { value: '' },
  D7: { value: '' },
  D8: { value: '' },
  D9: { value: '' },

  E1: { value: '' },
  E2: { value: '' },
  E3: { value: '' },
  E4: { value: '' },
  E5: { value: '' },
  E6: { value: '' },
  E7: { value: '' },
  E8: { value: '' },
  E9: { value: '' },

  F1: { value: '' },
  F2: { value: '' },
  F3: { value: '' },
  F4: { value: '' },
  F5: { value: '' },
  F6: { value: '' },
  F7: { value: '' },
  F8: { value: '' },
  F9: { value: '' },

  G1: { value: '' },
  G2: { value: '' },
  G3: { value: '' },
  G4: { value: '' },
  G5: { value: '' },
  G6: { value: '' },
  G7: { value: '' },
  G8: { value: '' },
  G9: { value: '' },

  H1: { value: '' },
  H2: { value: '' },
  H3: { value: '' },
  H4: { value: '' },
  H5: { value: '' },
  H6: { value: '' },
  H7: { value: '' },
  H8: { value: '' },
  H9: { value: '' },

  I1: { value: '' },
  I2: { value: '' },
  I3: { value: '' },
  I4: { value: '' },
  I5: { value: '' },
  I6: { value: '' },
  I7: { value: '' },
  I8: { value: '' },
  I9: { value: '' },
};

export const solved: Board = {
  A1: { value: '8' },
  A2: { value: '6' },
  A3: { value: '4' },
  A4: { value: '7' },
  A5: { value: '9' },
  A6: { value: '5' },
  A7: { value: '2' },
  A8: { value: '1' },
  A9: { value: '3' },
  B1: { value: '9' },
  B2: { value: '5' },
  B3: { value: '1' },
  B4: { value: '2' },
  B5: { value: '3' },
  B6: { value: '8' },
  B7: { value: '6' },
  B8: { value: '4' },
  B9: { value: '7' },
  C1: { value: '2' },
  C2: { value: '7' },
  C3: { value: '3' },
  C4: { value: '6' },
  C5: { value: '4' },
  C6: { value: '1' },
  C7: { value: '5' },
  C8: { value: '9' },
  C9: { value: '8' },
  D1: { value: '6' },
  D2: { value: '3' },
  D3: { value: '9' },
  D4: { value: '5' },
  D5: { value: '8' },
  D6: { value: '7' },
  D7: { value: '1' },
  D8: { value: '2' },
  D9: { value: '4' },
  E1: { value: '4' },
  E2: { value: '8' },
  E3: { value: '5' },
  E4: { value: '3' },
  E5: { value: '1' },
  E6: { value: '2' },
  E7: { value: '7' },
  E8: { value: '6' },
  E9: { value: '9' },
  F1: { value: '1' },
  F2: { value: '2' },
  F3: { value: '7' },
  F4: { value: '4' },
  F5: { value: '6' },
  F6: { value: '9' },
  F7: { value: '8' },
  F8: { value: '3' },
  F9: { value: '5' },
  G1: { value: '7' },
  G2: { value: '1' },
  G3: { value: '2' },
  G4: { value: '9' },
  G5: { value: '5' },
  G6: { value: '4' },
  G7: { value: '3' },
  G8: { value: '8' },
  G9: { value: '6' },
  H1: { value: '5' },
  H2: { value: '9' },
  H3: { value: '6' },
  H4: { value: '8' },
  H5: { value: '2' },
  H6: { value: '3' },
  H7: { value: '4' },
  H8: { value: '7' },
  H9: { value: '1' },
  I1: { value: '3' },
  I2: { value: '4' },
  I3: { value: '8' },
  I4: { value: '1' },
  I5: { value: '7' },
  I6: { value: '6' },
  I7: { value: '9' },
  I8: { value: '5' },
  I9: { value: '2' },
};
